apiVersion: v1
kind: Namespace
metadata:
  name: ebs-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-test-pvc
  namespace: ebs-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-storageclass
  resources:
    requests:
      storage: 4Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-test
  namespace: ebs-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebs-test
  template:
    metadata:
      labels:
        app: ebs-test
    spec:
      containers:
        - name: writer
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "started $(date)" >> /data/test.txt
              while true; do
                date >> /data/test.txt
                sleep 30
              done
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ebs-test-pvc
